# Generated by Django 4.1.3 on 2022-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_code_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
