# Generated by Django 4.1.3 on 2022-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(default='Presentación: ', max_length=300),
        ),
    ]
