# Generated by Django 4.1.3 on 2022-12-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(default='1Kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.CharField(max_length=300),
        ),
    ]
